### ISSUE TITLE
Trakt authentication doesn't work

### ISSUE THREAD

**Issue by ewan2395** [JvSomeren/tautulli-watched-sync#1]
Debian 9
Python 2.7.13

Running ` python trakt_letterboxd_sync.py --contentType trakt_authenticate --userId -1`

Results in:

```
Traceback (most recent call last):
  File "trakt_letterboxd_sync.py", line 479, in <module>
    trakt = Trakt(None, None)
TypeError: __init__() takes exactly 4 arguments (3 given)
```

**Comment by JvSomeren** [comment]
Thanks for notifying me and making a pull request!

If you run into any other issues please let me know :)

**Comment by ewan2395** [comment]
When Tautulli executes the script if fails due to a lack of userID in the arguments. 

I ran the script manually while adding the userID argument and it successfully added the episode to Trakt's watched history: 
`python /opt/plexutils/t2t/trakt_letterboxd_sync.py --userId 24231022 --contentType=episode --tvdbId=74709 --season=12 --episode=24`

I'm not 100% certain I have the correct variable for the userID in Tautulli but I have modified the argument used to trigger the script in Tautulli: 
`--userId {user_id} --contentType {media_type} <movie>--imdbId {imdb_id}</movie> <episode>--tvdbId {thetvdb_id} --season {season_num} --episode {episode_num}</episode>`

**Comment by JvSomeren** [comment]
You are 100% correct in your assumption. The README was indeed missing a required argument. I've made a commit updating the documentation, thanks again for your input!

The argument you show above should be correct and is the same as the one I'm using.

As for your userId, it should be visible as a GET parameter when viewing your user in the Tautulli webGUI. For example: `https://example.com/user?user_id=3837108`. To find to page go to your `Users` overview in Tautulli and click on a name/email.
