### ISSUE TITLE
Permission Denied?

### ISSUE THREAD

**Issue by bbakermmc** [JvSomeren/tautulli-watched-sync#3]
Tautulli Notifiers :: Failed to run script: [Errno 13] Permission denied

**Comment by bbakermmc** [comment]
chmod to 777 but  now:

Tautulli Notifiers :: Failed to run script: [Errno 8] Exec format error

Tautulli Notifiers :: Full script is: [u'/config/Scripts/trakt_letterboxd_sync.sh', '--userId', 'xxxxxxx', '--contentType', 'episode', '--tvdbId', '295648', '--season', '5', '--episode', '6']

**Comment by JvSomeren** [comment]
The problem seems to be with the extension used by your script `trakt_letterboxd_sync.sh`, this should be `trakt_letterboxd_sync.py`.
Try changing this, it should work with the correct extension.
