### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by enrique131** [JvSomeren/tautulli-watched-sync#6]
Is there any version (fork) of this that works as november 2022?

**Comment by JvSomeren** [comment]
It should still work! I use it to sync my watched movies and TV Shows without issues.

**Comment by enrique131** [comment]
Ok, i think i managed to advanced a little, i might have a stupid question about this part:
Under:
"Conditions: Tautulli > Settings > Notification Agents > New Script > Conditions:  
  Set Conditions: [{condition} | {operator} | {value} ]   --> Do i need to edit anything here?
![image](https://user-images.githubusercontent.com/45486873/200115920-ee9195d8-e1dc-450f-a3d6-5ede709b4ca2.png)
  Save
  
Script Arguments:
Tautulli > Settings > Notification Agents > New Script > Script Arguments:
  
  Select: Watched
  Arguments:  --userId {user_id} --contentType {media_type}
              <movie>--imdbId {imdb_id}</movie>
              <episode>--tvdbId {thetvdb_id} --season {season_num} --episode {episode_num}
</episode>
![image](https://user-images.githubusercontent.com/45486873/200116065-0bd22453-5a7b-4aaf-84d3-2d14845348c4.png)

And also, do I need to change here for my values of: user_id; thetvdb_id, etc?

And lastly: I have no account and no intention of using Letterboxd (already have too many apps to control tv and movies. Is there a way to fix that to be trakt only yet?

Thank you for your time to read and answer if possible

**Comment by JvSomeren** [comment]
> Under:
"Conditions: Tautulli > Settings > Notification Agents > New Script > Conditions:
Set Conditions: [{condition} | {operator} | {value} ] --> Do i need to edit anything here?

This can be left empty.

As for the arguments just enter the string below (no line breaks):
`--userId {user_id} --contentType {media_type} <movie>--imdbId {imdb_id}</movie><episode>--tvdbId {thetvdb_id} --season {season_num} --episode {episode_num}</episode>`

It should then look something like this under the "Preview" option.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/5375340/200117249-234f6d1a-087f-4d35-879e-abd14900cd8b.png">

The {user_id}, etc. values can be left as is. Tautulli will fill these when calling the script.

In your `sync_settings.ini`-file you need to enter your Plex user_id under `user_ids` and fill in the `Trakt` section of the file. More about this in the README.

> And lastly: I have no account and no intention of using Letterboxd (already have too many apps to control tv and movies. Is there a way to fix that to be trakt only yet?

You can just leave the Letterboxd section empty in your `sync_settings.ini`. Do note however that only TV Shows will be synced to Trakt.

**Comment by enrique131** [comment]
Thanks a lot for your time @JvSomeren:
In the configuration it says: under [Plex]
  user_ids: a comma separated list of user ids, only entries for these users will be synced (The user id for a user can be found in your url in _**Tautulli**_ when you click on a user).

But you wrote this above: 
"In your sync_settings.ini-file you need to enter your **_Plex user_id_** under user_ids and fill in the Trakt section of the file. More about this in the README."

I changed it to plex user as suggested and i think my trakt ID, secret, token and refresh token are ok (last one i assumed is the one i get from https://trakt.tv/oauth/applications): 
![image](https://user-images.githubusercontent.com/45486873/200118653-1efa7013-628f-4366-a111-9b4701c79b74.png)
the authorize result. 

Letterboxd and movies i can managed without it. That is easier that managing all tv shows. 

when testing i get:
![image](https://user-images.githubusercontent.com/45486873/200118724-a94f06ef-e2dc-4255-96d7-5acb7eb717f5.png)

which is better than it was before... it seems is going in a good way. 
Just in case someone reads this or is important for anything i am using synology docker and is the tautulli/tautulli  docker which i dont know if it has the js i think i have seen somewhere regarding scrobbling.

**Comment by enrique131** [comment]
Just to confirm... it is working as of 12 nov 2022

**Comment by pro4tlzz** [comment]
Thanks I might need this!
